<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="c">
      <HintPath>..\DLL\tyuiu.cources.programming.interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>
	<ItemGroup>
		<Content Include="..\DataSprint5\InPutDataFileTask4V25.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
